src/Entity/EnfantProfil.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EnfantProfilRepository")
 */
class EnfantProfil
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Range(min="now -1 year",max="now +6 year")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $allergie;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $traitement;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $maladies;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $autres;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Parentt", inversedBy="enfant")
     */
    private $parentt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Plan", mappedBy="enfantProfil")
     */
    private $plan;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(mimeTypes = {"image/jpeg", "application/pdf"})
     */
    private $acte_de_naissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(mimeTypes = {"image/jpeg", "application/pdf"})
     */
    private $certificat_de_grossesse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(mimeTypes = {"image/jpeg", "application/pdf"})
     */
    private $carnet_de_sante;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(mimeTypes = {"image/jpeg", "application/pdf"})
     */
    private $livret_de_famille_enfant;

    public function __construct()
    {
        $this->created_at = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this->plan = new ArrayCollection();
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAllergie(): ?string
    {
        return $this->allergie;
    }

    public function setAllergie(?string $allergie): self
    {
        $this->allergie = $allergie;

        return $this;
    }

    public function getTraitement(): ?string
    {
        return $this->traitement;
    }

    public function setTraitement(?string $traitement): self
    {
        $this->traitement = $traitement;

        return $this;
    }

    public function getMaladies(): ?string
    {
        return $this->maladies;
    }

    public function setMaladies(?string $maladies): self
    {
        $this->maladies = $maladies;

        return $this;
    }

    public function getAutres(): ?string
    {
        return $this->autres;
    }

    public function setAutres(?string $autres): self
    {
        $this->autres = $autres;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getParentt(): ?Parentt
    {
        return $this->parentt;
    }

    public function setParentt(?Parentt $parentt): self
    {
        $this->parentt = $parentt;

        return $this;
    }

    /**
     * @return Collection|Plan[]
     */
    public function getPlan(): Collection
    {
        return $this->plan;
    }

    public function addPlan(Plan $plan): self
    {
        if (!$this->plan->contains($plan)) {
            $this->plan[] = $plan;
            $plan->setEnfantProfil($this);
        }

        return $this;
    }

    public function removePlan(Plan $plan): self
    {
        if ($this->plan->contains($plan)) {
            $this->plan->removeElement($plan);
            // set the owning side to null (unless already changed)
            if ($plan->getEnfantProfil() === $this) {
                $plan->setEnfantProfil(null);
            }
        }

        return $this;
    }

    public function getActeDeNaissance(): ?string
    {
        return $this->acte_de_naissance;
    }

    public function setActeDeNaissance(?string $acte_de_naissance): self
    {
        $this->acte_de_naissance = $acte_de_naissance;

        return $this;
    }

    public function getCertificatDeGrossesse(): ?string
    {
        return $this->certificat_de_grossesse;
    }

    public function setCertificatDeGrossesse(?string $certificat_de_grossesse): self
    {
        $this->certificat_de_grossesse = $certificat_de_grossesse;

        return $this;
    }

    public function getCarnetDeSante(): ?string
    {
        return $this->carnet_de_sante;
    }

    public function setCarnetDeSante(?string $carnet_de_sante): self
    {
        $this->carnet_de_sante = $carnet_de_sante;

        return $this;
    }

    public function getLivretDeFamilleEnfant(): ?string
    {
        return $this->livret_de_famille_enfant;
    }

    public function setLivretDeFamilleEnfant(?string $livret_de_famille_enfant): self
    {
        $this->livret_de_famille_enfant = $livret_de_famille_enfant;

        return $this;
    }
}

templates/parent/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil Parent{% endblock title %}

{% block body %}
    <div class="clear"></div>
    {{ parent() }}
    <div class="container mt-5 mb-5 align-center text-center" style="padding-top: 100px;">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 align-center text-center">
                <label for="" class="mb-2 h2" style="width: 100%;">Rechercher nos différents professionnels par code postale</label>
                <input id='test' type="text" value="" style="width: 100%;">
                <input type="submit" id="envoie" class="btn  hmed" value="Envoyer" style="width: 100%;">
            </div>
            <div class="col-md-3"></div>

        </div>


        <!-- Content here -->
       <a href="{{ path('subs') }}" class="condi">
            <button type="button" class="btn  hmed">Abonnement</button>
        </a>
    </div>

    {#profil#}
    <div class="container ">
        <div class="row">

            {% for flash_message in app.session.flashBag.get('success') %}
                <div class="alert alert-success text-center">
                    {{ flash_message }}
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="container text-center  mb-2">
                    <div class="row ">
                        <div class="col-md h1" style="border-radius: 30px; padding: 5%;">Profil</div>
                        <p>Si vous souhaitez communiquer avec nos différents professionnels, il est fortement conseillé de remplir votre profil</p>
                    </div>
                </div>
                <ul class="list-group mb-3">
                    <li class="list-group-item"><span class="text-info font-weight-bold">Nom : </span>{{ parent.nom }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Prénom : </span>{{ parent.prenom }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Adresse : </span>{{ parent.adresse }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Téléphone : </span>{{ parent.telephone }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Email : </span>{{ parent.mail }}</li>
                    <li class="list-group-item"><a href="{{ asset('fichiers/parents/revenus/') }}{{ parent.revenu }}" target="_blank">Les Derniers Revenus</a></li>
                    <li class="list-group-item"><a href="{{ asset('fichiers/parents/impots/') }}{{ parent.impots }}">Fiche d'impôts</a></li>
                    <li class="list-group-item"><a href="{{ asset('fichiers/parents/caf/') }}{{ parent.attestationcaf }}">CAF</a></li>
                    <li class="list-group-item"><a href="{{ asset('fichiers/parents/justificatifdomicile/') }}{{ parent.justificatifdomicile }}">Justification de domicile</a></li>
                    <li class="list-group-item"><a href="{{ asset('fichiers/parents/livretdefamille/') }}{{ parent.livretdefamille }}">Livret de Famille</a></li>
                </ul>
                <br><a href="{{ path('editparent', { 'id' : app.user.id }) }}">
                    <button type="button" class="btn hmed ">Modifier</button>
                     </a>
                     <a href="{{ path('modifpassword', { 'id' : app.user.id }) }}">
                         <button type="button" class="btn hmed ">Modifier mot de passe</button>
                     </a>
                </div>

            {#profil enfant#}
            <div class="col-md-4 offset-md-4">
                <div class="col-md h1 text-center mb-2">Vos Enfants</div>


                <table class="table profil">
                    <thead class="thead-light font-weight-bold">
                    <tr>
                        <th scope="col">Prénom</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Editer</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>

                    {% if data is defined %}
                    {% for enfant in data %}
                    <tbody>
                    <tr class="table-primary">
                        <th>{{ enfant.prenom }}</th>
                        <th>{{ enfant.nom }}</th>
                        <th>
                            <a href="{{ path('editsenfant', { 'id' : app.user.id, 'enfant_id' : enfant.id }) }}">Modifier</a>
                        </th>
                        <th>
                            <a href="{{ path('showenfant', { 'id' : app.user.id, 'enfant_id' : enfant.id }) }}">Voir</a>
                        </th>
                    </tr>
                    </tbody>
                    {% endfor %}
                    {% endif %}



                </table>
                <div class="text-center">
                    <a href="">
                        <a href="{{ path('créerenfant', { 'id' : app.user.id }) }}"><button type="button" class="btn  text-right hmed  ">Ajouter</button></a>
                    </a>
                </div>
            </div>
        </div>

{#liste des demande de creche#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-2" style="border-radius: 30px; padding: 5%;">Liste des demandes</div>

                </div>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <table class="table">
                    <thead class="hmed font-weight-bold">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nom du professionnel</th>
                        <th scope="col">date de demande</th>
                        <th scope="col">statut</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Crêche du nord</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Crêche du sud</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Crêche de l'ouest</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>Crêche de l'est</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    </tbody>
                </table>
                {#   HERE#}

            </div>
        </div>


{#liste d'attente#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-2" style="border-radius: 30px; padding: 5%;">Liste d'attente</div>
                </div>
            </div>
        </div>
        <div class="container mt-3">
            <div class="row">
                <table class="table">
                    <thead class="hmed font-weight-bold">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nom du professionnel</th>
                        <th scope="col">date de demande</th>
                        <th scope="col">statut</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Crêche du nord</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Crêche du sud</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Crêche de l'ouest</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>Crêche de l'est</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    </tbody>
                </table>
                {#   HERE#}

            </div>
        </div>

        {#liste des avis#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-4" style="border-radius: 30px; padding: 5%;">Liste des avis</div>
                </div>
            </div>
        </div>
        <div class="row" >

            <div class="col-md-4">

                <div class="panel panel-default p-2 panel-index-color" style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2" ><h3>Avis 1</h3></div>
                    <div class="panel-body">Mes enfants ont était gardé par la crêche du nord je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default p-2 panel-index-color" style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2"><h3>Avis 2</h3></div>
                    <div class="panel-body">Mes enfants ont était gardé par la crêche du sud je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default p-2 panel-index-color " style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2"><h3>Avis 3</h3></div>
                    <div class="panel-body">Mes enfants ont était gardé par la crêche de l'ouest je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>
            <div class="col-md-6 offset-md-3 mt-3">
                <a href="{{ path ('review') }}" class="btn hmed btn-block mt-3 mb-3">Voir tous les avis</a>
            </div>
        </div>
    </div>



{% endblock body %}


{% block javascripts %}
    {{ parent() }}
    <script>


       var t = $('#envoie').click(function ()
       {
           let y = $('#test').val();


           window.location.href = 'http://127.0.0.1:8000/map/' + y;


            $.ajax({
                url: 'http://127.0.0.1:8000/map/' + y,
                type: 'POST',
                dataType: 'html',
                success: function (y) {
                    window.location.replace('http://127.0.0.1:8000/map/' + y)
                }
            })

       });


    </script>

{% endblock javascripts %}

templates/parent/edit_child.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Enfant{% endblock title %}

{% block body %}
    <div class="clear"></div>
    {{ parent() }}
    <div class="contentform">
        <div class="row">
            {% if error %}
                <div class="alert alert-danger">
                    <ul class="list-unstyled mb-0">
                        <li><span class="initialism badge-danger badge">Error</span>
                            <span class="error">{{ error.messageKey| trans(error.messageData, 'security') }}</span>
                        </li>
                    </ul>
                </div>
            {% endif %}
            <div class="col-md-12">
                {{ form_start(form) }}
                <h1 class="text-center">Renseigner le profil de votre enfant</h1>
                <hr class="colorgraph">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.nom,{'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.prenom, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{ form_row(form.dateNaissance, { 'attr': { 'class' : 'col-xs-12 col-sm-6 col-md-6'}}) }}
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.maladies, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.traitement, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.allergie) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_row(form.autres) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_label(form.acteDeNaissance, 'Acte de naissance (PDF/JPEG)', {
                                'label_attr': {'class': 'lab'}
                            }) }}
                            {{ form_widget(form.acteDeNaissance, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}

                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_label(form.certificatDeGrossesse, 'Certificat de grossesse (PDF/JPEG)', {
                                'label_attr': {'class': 'lab'}
                            }) }}
                            {{ form_widget(form.certificatDeGrossesse) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_label(form.carnetDeSante, 'Carnet de santé (PDF/JPEG)', {
                                'label_attr': {'class': 'lab'}
                            }) }}
                            {{ form_widget(form.carnetDeSante) }}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{ form_label(form.livretDeFamilleEnfant, 'Livret de famille de l\'enfant (PDF/JPEG)', {
                                'label_attr': {'class': 'lab'}
                            }) }}
                            {{ form_widget(form.livretDeFamilleEnfant) }}

                        </div>
                    </div>
                </div>

                <hr class="colorgraph">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <input class="btn btn-success btn-block pb-lg-4" type="button" onclick="location.href='{{ path('dashboardparent', {'id' : app.user.id}) }}';" value="Retour" />
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <input type="submit" class="btn btn-success btn-block pb-lg-4" value="Enregistrer">
                    </div>

                </div>

            </div>
        </div>

    </div>

{% endblock body %}

templates/parent/profil_child.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'enfants{% endblock title %}

{% block body %}
    <div class="clear"></div>
    {{ parent() }}
        <div class="contentform">
            <div class="row">
                {% if error %}
                    <div class="alert alert-danger">
                        <ul class="list-unstyled mb-0">
                            <li><span class="initialism badge-danger badge">Error</span>
                                <span class="error">{{ error.messageKey| trans(error.messageData, 'security') }}</span>
                            </li>
                        </ul>
                    </div>
                {% endif %}
                <div class="col-md-12">
                    {{ form_start(form) }}
                        <h1 class="text-center">Renseigner le profil de votre enfant</h1>
                        <hr class="colorgraph">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.nom,{'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.prenom, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form_row(form.dateNaissance, { 'attr': { 'class' : 'col-xs-12 col-sm-6 col-md-6'}}) }}
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.maladies, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.traitement, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.allergie) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_row(form.autres) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.acteDeNaissance, 'Acte de naissance (PDF/JPEG)', {
                                        'label_attr': {'class': 'lab'}
                                    }) }}
                                    {{ form_widget(form.acteDeNaissance, {'attr' : { 'class' : 'form-control input-lg mt-3'}}) }}

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.certificatDeGrossesse, 'Certificat de grossesse (PDF/JPEG)', {
                                        'label_attr': {'class': 'lab'}
                                    }) }}
                                    {{ form_widget(form.certificatDeGrossesse) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.carnetDeSante, 'Carnet de santé (PDF/JPEG)', {
                                        'label_attr': {'class': 'lab'}
                                    }) }}
                                    {{ form_widget(form.carnetDeSante) }}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    {{ form_label(form.livretDeFamilleEnfant, 'Livret de famille de l\'enfant (PDF/JPEG)', {
                                        'label_attr': {'class': 'lab'}
                                    }) }}
                                    {{ form_widget(form.livretDeFamilleEnfant) }}

                                </div>
                            </div>
                        </div>

                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <input class="btn btn-success btn-block pb-lg-4" type="button" onclick="location.href='{{ path('dashboardparent', {'id' : app.user.id}) }}';" value="Retour" />
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <input type="submit" class="btn btn-success btn-block pb-lg-4" value="Enregistrer">
                        </div>

                    </div>

                </div>
            </div>

        </div>

{% endblock body %}

templates/parent/waitinglist.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ parent() }}


    {#   HERE#}



{% endblock body %}