src/Entity/ProProfil.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProProfilRepository")
 * @UniqueEntity(fields={"mail"},
 *     errorPath="mail",
 *     message="Cette adresse mail existe déjà!",
 * )
 * @UniqueEntity(fields={"nom_entreprise"},
 *     errorPath="nom_entreprise",
 *     message="Ce nom d'entreprise existe déjà"
 * )
 */
class ProProfil implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     *
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     *@Assert\Email(
     *   checkMX = true
     *)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     */
    private $codepostal;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Range(min=1,max=300)
     */
    private $nombre_personnel;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disponibilite = 1;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=10, nullable=true)
     */
    private $tarif;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $horaire = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombredeplace;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ListeStatus", mappedBy="proProfil")
     */
    private $listestatus;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Paiement", mappedBy="proProfil")
     */
    private $paiement;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Avis", mappedBy="proProfil")
     */
    private $avis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Facturation", mappedBy="proProfil")
     */
    private $facturation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tuteur", mappedBy="proProfil")
     */
    private $tuteur;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Plan", mappedBy="proProfil")
     */
    private $plan;

    /**
     * @ORM\Column(type="array")
     */
    private $roles =[];

    /**
     * @ORM\Column(type="decimal", precision=10, scale=10, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=10, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @Assert\File(mimeTypes={"image/jpeg", "image/png"})
     */
    private $avatar;

    public function __construct()
    {
        $this->created_at = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this->listestatus = new ArrayCollection();
        $this->paiement = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->facturation = new ArrayCollection();
        $this->tuteur = new ArrayCollection();
        $this->plan = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getnomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setnomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodepostal(): ?int
    {
        return $this->codepostal;
    }

    public function setCodepostal(?int $codepostal): self
    {
        $this->codepostal = $codepostal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getNombrePersonnel(): ?int
    {
        return $this->nombre_personnel;
    }

    public function setNombrePersonnel(?int $nombre_personnel): self
    {
        $this->nombre_personnel = $nombre_personnel;

        return $this;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getTarif()
    {
        return $this->tarif;
    }

    public function setTarif($tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getHoraire(): ?array
    {
        return $this->horaire;
    }

    public function setHoraire(?array $horaire): self
    {
        $this->horaire = $horaire;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNombredeplace(): ?int
    {
        return $this->nombredeplace;
    }

    public function setNombredeplace(int $nombredeplace): self
    {
        $this->nombredeplace = $nombredeplace;

        return $this;
    }

    /**
     * @return Collection|ListeStatus[]
     */
    public function getListestatus(): Collection
    {
        return $this->listestatus;
    }

    public function addListestatus(ListeStatus $listestatus): self
    {
        if (!$this->listestatus->contains($listestatus)) {
            $this->listestatus[] = $listestatus;
            $listestatus->setProProfil($this);
        }

        return $this;
    }

    public function removeListestatus(ListeStatus $listestatus): self
    {
        if ($this->listestatus->contains($listestatus)) {
            $this->listestatus->removeElement($listestatus);
            // set the owning side to null (unless already changed)
            if ($listestatus->getProProfil() === $this) {
                $listestatus->setProProfil(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Paiement[]
     */
    public function getPaiement(): Collection
    {
        return $this->paiement;
    }

    public function addPaiement(Paiement $paiement): self
    {
        if (!$this->paiement->contains($paiement)) {
            $this->paiement[] = $paiement;
            $paiement->setProProfil($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): self
    {
        if ($this->paiement->contains($paiement)) {
            $this->paiement->removeElement($paiement);
            // set the owning side to null (unless already changed)
            if ($paiement->getProProfil() === $this) {
                $paiement->setProProfil(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setProProfil($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->contains($avi)) {
            $this->avis->removeElement($avi);
            // set the owning side to null (unless already changed)
            if ($avi->getProProfil() === $this) {
                $avi->setProProfil(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Facturation[]
     */

src/Controller/ProController.php
<?php


namespace App\Controller;


use App\Entity\Plan;
use App\Entity\ProProfil;
use App\Form\PlanFormType;
use App\Form\ProProfilFormType;
use App\Repository\PlanRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class ProController extends AbstractController
{

    /**
     * @Route("/pro/dashboard/{id}", name="prodashboard")
     */
    public function dashboard(ProProfil $proProfil)
    {

        return $this->render('pro/pro_dashboard.html.twig', [
            'pro' => $proProfil,
            'avatar' => $proProfil->getAvatar()
        ]);
    }

    /**
     * @Route("/pro/{id}/show/planning", name="voirplanning")
     */
    public function showPlanning(ProProfil $proProfil, PlanRepository $planRepository)
    {
        $test = $planRepository->findByPro($proProfil->getId());

        return $this->render('pro/show_planning.html.twig', [
            'test' => $test,
        ]);

    }

    /**
     * @Route("/pro/profil/{id}/edit", name="editproprofil")
     */
    public function editprofil(Request $request, ProProfil $proProfil)
    {
        $form = $this->createForm(ProProfilFormType::class, $proProfil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            if($proProfil->getAdresse() != $form->get("adresse") || $proProfil->getCodepostal() != $form->get("codepostal") || $proProfil->getVille() != $form->get("ville"))
            {
                $street = $form->get("adresse")->getViewData();
                $ville = $form->get("ville")->getViewData();
                $codepostal = $form->get("codepostal")->getViewData();
                $adress = array(
                    'street'    => $street,
                    'city'      => $ville,
                    'postalcode'=>  $codepostal,
                    'country'   =>  'France',
                    'format'    =>  'json'
                );
                // Création d'une nouvelle ressource cURL
                $ch = curl_init("https://nominatim.openstreetmap.org/?". http_build_query($adress));
                // Configuration de l'URL et d'autres options
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_USERAGENT, 'Mettre ici un user-agent adéquat');
                // Récupération de l'URL et affichage sur le navigateur
                $g = curl_exec($ch);
                // Fermeture de la session cURL
                curl_close($ch);
                $json_data = json_decode($g,true);
                $proProfil->setLatitude($json_data[0]['lat']);
                $proProfil->setLongitude($json_data[0]['lon']);
                dump($adress);
            }

            //On créer notre variable file pour utiliser les propriétes
            /** @var UploadedFile $file */
            $file = $form->get('avatar')->getData();
            if (isset($file)){

                //On créer notre chaîne de caractère pour notre image upload
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                //On effectue le déplacement si c'est bon
                try{
                    $file->move(
                        $this->getParameter('avatar_directory'),
                        $fileName
                    );
                } catch (FileException $exception){

                }
                //On enregistre la chaîne de caractère dans notre bdd avec l'entité
                $proProfil->setAvatar($fileName);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($proProfil);
            $em->flush();

            dump($form);


            return $this->redirectToRoute('prodashboard', [
                'id' => $proProfil->getId()
            ]);
        }

        return $this->render('pro/pro_profil.html.twig', [
            'form' => $form->createView()
        ]);

    }

    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }

    /**
     * @Route("/pro/{id}/modifmotdepasse", name="modifpasswordpro")
     */
    public function modifpassword(Request $request, $id, UserPasswordEncoderInterface $encoder)
    {

        if ($request->isMethod("POST"))
        {
            $em = $this->getDoctrine()->getManager();
            $um = $em->getRepository(ProProfil::class)->findOneBy(["id" => $id]);

            $old = $request->request->get('old_password');
            $new = $request->request->get('new_password');
            $confirme = $request->request->get('confirm_new_password');

            if ($encoder->isPasswordValid($um,$old))
            {
                if ($new === $confirme)
                {
                    $um->setPassword($encoder->encodePassword($um, $confirme));

                    $em->flush();


                    $test = $this->addFlash("success", "Votre mot de passe à bien été modifier !");

                    return $this->redirectToRoute("prodashboard",[
                        'id' => $id,
                        'test'=> $test
                    ]);

                }else
                {
                    $this->addFlash("danger", "Erreur de confirmation mot de passe");
                }


            }else{
                $this->addFlash("danger", "Erreur de l'ancien mot de passe");
            }



        }

        return $this->render("pro/modifmotdepasse_pro.html.twig");

    }
    
   /**
     * @Route("/pro/{id}/planning/create", name="creerplanning")
     */
    public function ajoutPlanning(Request $request, ProProfil $proProfil)
    {
        $plan = new Plan();
        $id = $proProfil->getId();
        $form = $this->createForm(PlanFormType::class, $plan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            $plan->setProProfil($proProfil);

            $em = $this->getDoctrine()->getManager();
            $em->persist($plan);
            $em->flush();

            $test = $this->addFlash('success', 'Votre planning a bien été ajouté!');

            return $this->redirectToRoute('prodashboard', [
                'id' => $id,
                'test' => $test
            ]);
        }

        return $this->render('pro/formulaire_planning.html.twig', [
            'form' => $form->createView()
        ]);



    }

    /**
     * @Route("/indexpro/calendar/{id}", name="loadcalendar")
     * @return JsonResponse
     */
    public function LoadEvent(PlanRepository $test, $id)
    {


        $evenements = $test->findByPro($id);



        foreach ($evenements as $row){

            $data[] = array(
                'id' => $row['id'],
                'title' => utf8_encode($row['nom'] .' '. $row['prenom']),
                'start' => $row['heuredebut']->format('Y-m-d H:i'),
                'end' => $row['heuredefin']->format('Y-m-d H:i')
            );

        }

        return new JsonResponse($data);

    }

    /**
     * @Route("/logout", name="logout")
     */
    public function logout()
    {

    }

}

templates/pro/formulaire_planning.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout de planning{% endblock title %}

{% block body %}
    <div class="clear"></div>
    {{ parent() }}
    {{ form_start(form) }}
    <h1 class="text-center mt-5">Planning</h1>
    <div class="contentform">
        <div class="form-group">
            {{form_row(form.enfantProfil)}}
        </div>

        <div class="form-group">
            {{form_row(form.heuredebut)}}
        </div>

        <div class="form-group">
            {{form_row(form.heuredefin)}}
        </div>


        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <button type="submit" class="bouton-contact">Enregistrer</button>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <a href="{{ path('prodashboard', { 'id' : app.user.id }) }}">
                    <button type="button" class="bouton-contact">Retour</button>
                </a>
            </div>
        </div>
                {{ form_end(form) }}


    </div>

{% endblock body %}

templates/pro/pro_dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock title %}

{% block body %}
<div class="clear"></div>
    {{ parent() }}
    <div class="container mt-5 mb-5 text-center" style="padding-top: 100px">
        <a href=""><button type="button" class="btn hmed">Abonnement</button></a>
    </div>

    {#profil#}
    <div class="container ">
        <div class="row">

            {% for flash_message in app.session.flashBag.get('success') %}
                <div class="alert alert-success text-center">
                    {{ flash_message }}
                </div>
            {% endfor %}
        </div>
        <div class="row">
        
          <div class="col-md-4"></div>
            
            <div class="col-md-5">
                <div class="container text-center mb-2">
                    <div class="row ">
                        <div class="col-md h1" style="border-radius: 30px; padding: 5%;">Profil</div>
                        <p>Veuillez remplir vos informations pour que les parents puissent vous retrouver via notre système de recherche par géolocalisation</p>
                    </div>
                </div>
                <ul class="list-group mb-3">
                    <li class="list-group-item"><span class="text-info font-weight-bold">Nom : </span> {{ pro.nomEntreprise }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Adresse : </span>{{ pro.adresse }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">vIlle : </span>{{ pro.ville }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Code Postal : </span>{{ pro.codepostal }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Téléphone : </span>{{ pro.telephone }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Email : </span>{{ pro.mail }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Disponibilité : </span> {{ pro.disponibilite ? 'OUI' : 'NON' }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Nombre de places : </span>{{ pro.nombredeplace }}</li>
                    <li class="list-group-item"><span class="text-info font-weight-bold">Nombre d'employés : </span>{{ pro.nombrePersonnel }}</li>
                </ul>
                <a href="{{ path('editproprofil', {'id': app.user.id }) }}">
                    <button type="button" class="btn hmed">Modifier</button>
                </a>
                <a href="{{ path('modifpasswordpro', { 'id' : app.user.id }) }}">
                    <button type="button" class="btn hmed ">Modifier mot de passe</button>
                <a href="{{ path('creerplanning', { 'id' : app.user.id}) }}">
                    <button type="submit" class="btn hmed">Ajouter planning</button>
                </a>
                <a href="{{ path('voirplanning', { 'id' : app.user.id }) }}">
                    <button type="submit" class="btn hmed">Voir les plannings</button>
                </a>
            </div>
            {#profil enfant#}
            <div class="col-md-3 offset-md-4">
                <div class="profile-img">
                    <img src="{{ asset('images/avatar/') }}{{ pro.avatar }}" alt="">
                    </div>
                </div>
            </div>
        <h1 class="text-uppercase text font-weight-bold">Voici le calendrier visuel pour avoir un visuel direct sur vos journées qui sont occupées</h1>
        <div id="calendar" class="mt-5"></div>
        {#liste des demande de creche#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-2" style="border-radius: 30px; padding: 5%;">Liste des demandes</div>

                </div>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <table class="table">
                    <thead class="hmed font-weight-bold">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nom du particulier</th>
                        <th scope="col">date de demande</th>
                        <th scope="col">statut</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>?;?</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>;?;</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>!:!</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>:!:</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    </tbody>
                </table>
                {#   HERE#}
                <div class="col-md-6 offset-md-3 mt-3">
                    <a href="#" class="btn hmed btn-block mt-3 mb-3">Voir vos demandes</a>
                </div>
            </div>
        </div>

{#liste des membres #}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-2" style="border-radius: 30px; padding: 5%;">Liste des membres</div>

                </div>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <table class="table">
                    <thead class="hmed font-weight-bold">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nom du parent</th>
                        <th scope="col">Prénom du parent</th>
                        <th scope="col">Prénom de l'enfant</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>?;?</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>;?;</td>
                        <td>10/08/1989</td>
                        <td>Refusé</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>!:!</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>:!:</td>
                        <td>10/08/1989</td>
                        <td>Accepté</td>
                    </tr>
                    </tbody>
                </table>
                {#   HERE#}
                <div class="col-md-6 offset-md-3 mt-3">
                    <a href="#" class="btn hmed btn-block mt-3 mb-3">Voir vos membres</a>
                </div>
            </div>
        </div>

        {#liste d'attente#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-2" style="border-radius: 30px; padding: 5%;">Liste d'attente</div>
                </div>
            </div>
        </div>
        <div class="container mt-3">
            <div class="row">
                <table class="table">
                    <thead class="hmed font-weight-bold">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nom du particulier</th>
                        <th scope="col">date de demande</th>
                        <th scope="col">statut</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>,;,</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>;,;</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>$/$</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    <tr>
                        <th scope="row">4</th>
                        <td>/$/</td>
                        <td>10/08/1989</td>
                        <td>En attente</td>
                    </tr>
                    </tbody>
                </table>
                {#   HERE#}
                <div class="col-md-6 offset-md-3 mt-3">
                    <a href="#" class="btn hmed btn-block mt-3 mb-3">Voir votre liste d'attente</a>
                </div>
            </div>
        </div>

        {#liste des avis#}
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="col-md h1 text-center mb-4" style="border-radius: 30px; padding: 5%;">Liste des avis</div>
                </div>
            </div>
        </div>
        <div class="row" >

            <div class="col-md-4">

                <div class="panel panel-default p-2 panel-index-color" style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2" ><h3>Avis 1</h3></div>
                    <div class="panel-body">Mes enfants ont étaient gardé par la crêche du nord je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default p-2 panel-index-color" style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2"><h3>Avis 2</h3></div>
                    <div class="panel-body">Mes enfants ont étaient gardé par la crêche du nord je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-default p-2 panel-index-color " style="background-color: #eee;">
                    <div class="panel-heading text-sm-center mb-2"><h3>Avis 3</h3></div>
                    <div class="panel-body">Mes enfants ont étaient gardé par la crêche du nord je remercie super nany pour son travail c'est un endroit que je conseille

                    </div>
                </div>
            </div>
            <div class="col-md-6 offset-md-3 mt-3">
                <a href="#" class="btn hmed btn-block mt-3 mb-3">Voir tous les avis</a>
            </div>
        </div>
    </div>

{% endblock body %}